todoproj/todoproj/todoapp/urls.py
from django.urls import path
from . import views
app_name='todoapp'
urlpatterns = [

    path('',views.add,name='add'),
    path('delete/<int:taskid>/',views.delete,name='delete'),
    path('update/<int:id>/',views.update,name='update'),
    path('cbvhome/',views.Tasklistview.as_view(),name='cbvhome'),
    path('cbvdetail/<int:pk>/',views.Taskdetailview.as_view(),name='cbvdetail'),
    path('cbvupdate/<int:pk>/',views.Taskupdateview.as_view(),name='cbvupdate'),
    path('cbvdelete/<int:pk>/',views.Taskdeleteview.as_view(),name='cbvdelete'),
]

todoproj/todoproj/todoproj/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls')),
]

todoproj/todoproj/todoapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=250, null=False)
    priority = models.IntegerField()
    date=models.DateField()
    def __str__(self):
        return self.name

todoproj/todoproj/todoapp/forms.py
from .models import Task
from django import forms

class TodoForm(forms.ModelForm):
    class Meta:
        model=Task
        fields=['name','priority','date']

todoproj/todoproj/todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .models import Task
from .forms import TodoForm
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView

class Tasklistview(ListView):
    model=Task
    template_name = 'home.html'
    context_object_name = 'task'

class Taskdetailview(DetailView):
    model=Task
    template_name = 'details.html'
    context_object_name = 'task'

class Taskupdateview(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ('name','priority','date')
    def get_success_url(self):
        return reverse_lazy('cbvdetail',kwargs={'pk':self.object.id})

class Taskdeleteview(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('cbvhome')
#create your views here
def add(request):
    tasks = Task.objects.all()
    if request.method=='POST':
        name = request.POST.get('name','')
        priority = request.POST.get('priority','')
        date = request.POST.get('date','')
        task = Task(name=name,priority=priority,date=date)
        task.save()
    return render(request,'home.html',{'task':tasks})
# def details(request):
#
#     return render(request,'details.html',)
def delete(request,taskid):
    if request.method == 'POST':
        task = Task.objects.get(id=taskid)
        task.delete()
        return redirect('/')
    return render(request,'delete.html')

def update(request,id):
        task = Task.objects.get(id=id)
        f=TodoForm(request.POST or None, instance=task)
        if f.is_valid():
            f.save()
            return redirect('/')
        return render(request,'edit.html',{'f':f,'task':task})

todoproj/todoproj/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
     <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

todoproj/todoproj/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" class="p-3 shadow">
                {% csrf_token %}
    <p>Are you sure this task is done?</p>
    <input type="submit">
</form>
{% endblock %}

todoproj/todoproj/templates/details.html
{% extends 'base.html' %}
{% block content %}
<div class="shadow card">
                <div class="card-body">
                    <h5 class="card-title">{{ task.name }}</h5>
                    <p><b>{{ task.priority }}</b></p>
                    <p><b>{{ task.date }}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' task.id %}">Done</a>
                    <a class="btn btn-success" href="{% url 'todoapp:update' task.id %}">Update</a>
                </div>
            </div>
{% endblock %}

todoproj/todoproj/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" class="p-3 shadow">
                {% csrf_token %}
    {{f.as_p}}
    <input type="submit">
</form>
{% endblock %}

todoproj/todoproj/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner" style="background-color:darkslateblue;width:100%;
    height:200px;margin-bottom:50px;">
                <div class="banner-text" style="top:50%;left:50%;position:relative;transform:transform;">
                    <h1>ToDo</h1>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="POST" class="p-3 shadow">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" name="name" placeholder="Task">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="priority" placeholder="Enter priority">
                </div>
                <div class="form-group">
                    <input type="date" class="form-control" name="date" placeholder="Enter Date">
                </div>
                <input type="submit" class="btn btn-success">
            </form>
        </div>

        <div class="col-md-6">
            <h4>Tasks to be completed</h4>
            {% for i in task %}
            <div class="shadow card">
                <div class="card-body">
                    <h5 class="card-title">{{ i.name }}</h5>
                    <p><b>{{ i.priority }}</b></p>
                    <p><b>{{ i.date }}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">Done</a>
                    <a class="btn btn-success" href="{% url 'todoapp:update' i.id %}">Update</a>
                </div>
            </div>
            <br>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

todoproj/todoproj/templates/update.html
{% extends 'base.html' %}
{% block content %}
<div class="card">
    <div class="card-header">
        <div class="card-title">
            Task Update
        </div>
        <div class="card-body">
            <form method="POST" class="p-3 shadow">
                {% csrf_token %}
                {{form.as_p}}
    <button type="submit">Confirm</button>
</form>
        </div>
    </div>
</div>

{% endblock %}